name: Update Bible Verse

on:
  schedule:
    - cron: "0 10 * * *" # todos os dias às 10h UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Run bible verse updater
        run: |
          node .github/scripts/update-bibleverse.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git commit -m "🔄 update: daily bible-verse" || echo "No changes to commit"
          git push
